### ISSUE TITLE
Incorrect 'msgid' instances

### ISSUE THREAD

**Issue by MiroslavR** [SuperTux/translations#1]
Basing PO files off of these templates results in strings containing newlines not being translated in-game. This is due to the presence of carriage returns in source strings, which are not expected:

> [TINYGETTEXT] Couldn't translate: -Bonus Blocks
> !images/objects/bonus_block/full-0.png
> # Bonus blocks can contain coins, power-ups or special items to help you in your quest.
> # 
> # Hit them from below to get at their contents.

As a result, translators cannot use PO files downloaded from Transifex to test all of their translations. They have to replace all instances of '\r\n' with '\n' to see strings with newlines translated in-game.

**Comment by tobbi** [comment]
I will try to fix this in the extract script.

**Comment by tobbi** [comment]
I have fixed the strings and added a proper replacement to the makepot.sh file. Updating on transifex should take place within 24 hours.
